from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import Tuple

CONDA_CHANNELS: Tuple[str, ...] = (
    "conda-forge",
    "nodefaults",
)
CONDA_DEPENDENCIES: Tuple[str, ...] = (
    "astropy",
    "autobahn",
    "automake",
    "bandit",
    "cfitsio",
    "cmake",
    "compilers",
    "configobj",
    "coveralls",
    "cython",
    "deprecation",
    "ephem",
    "fftw",
    "flake8",
    "flatbuffers",
    "h5py",
    "healpy",
    "influxdb",
    "ipykernel",
    "lapack",
    "libaatm",
    "libsharp",
    "libtool",
    "make",
    "matplotlib",
    "mpi4py",
    "mpich-mpicc",
    "mpich-mpicxx",
    "mpich-mpifort",
    "mypy",
    "nbformat",
    "numba",
    "numpy",
    "pillow",
    "plotly",
    "pshmem",
    "py-ubjson",
    "pyaml",
    "pydocstyle",
    "pyfftw",
    "pylint",
    "pyserial",
    "pysm3",
    "pysmi",
    "pysnmp",
    "pysqlite3",
    "pytest",
    "pytest-cov",
    "python-dateutil",
    "pytz",
    "pyyaml",
    "quaternionarray",
    "scikit-image",
    "scipy",
    "setproctitle",
    "setuptools",
    "skyfield",
    "sphinx",
    "sphinx_rtd_theme",
    "sqlalchemy",
    "suitesparse",
    "toml",
    "tqdm",
    "twisted",
    "typer",
    "ujson",
    "wurlitzer",
)
DEPENDENCIES: Tuple[str, ...] = (
    "libmadam",
    "toast",
)
