name: Integration test

on:
  pull_request:
  push:
  schedule:
      - cron: '12 1 * * 6'

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: "windows"
            extra-args: --no-install-ipykernel
          - os: "ubuntu"
          - os: "macos"
    defaults:
      run:
        shell: bash -l {0}
    name: conda_install on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      # set ENV_FILE to the path of the environment file according to the OS
      - name: Set ENV_FILE
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu" ]]; then
            ENV_FILE=examples/linux.yml
          elif [[ "${{ matrix.os }}" == "windows" ]]; then
            ENV_FILE=examples/windows.yml
          elif [[ "${{ matrix.os }}" == "macos" ]]; then
            ENV_FILE=examples/macos.yml
          fi
          echo "ENV_FILE=$ENV_FILE" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          mamba-version: "*"
          channels: conda-forge
          environment-file: environment.yml
      - name: Install pmpm
        run: pip install .
      - name: test
        run: pmpm conda_install "$HOME/pmpm-test" --file $ENV_FILE ${{ matrix.extra-args }}
        env:
          # c.f. https://github.com/hpc4cmb/toast/blob/eb1e65097f99ecac63d8976f7131764a43a7ff07/src/toast/tests/runner.py#L113-L117
          CIBUILDWHEEL: 1
