name: test with conda

on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
    name: test with conda on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge
          auto-activate-base: true
          activate-environment: ""
          environment-file: environment.yml
      - name: test
        run: |
          conda activate pmpm
          pmpm conda_install "$HOME/pmpm-test"
