name: Integration test (small)

on:
  pull_request:
  push:
  schedule:
      - cron: '12 1 * * 6'

jobs:
  test:
    strategy:
      fail-fast: true
      # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
      matrix:
        include:
          - os: "windows-2022"
            python-version: "3.8"
          - os: "macos-11"
            python-version: "3.9"
          - os: "macos-12"
            python-version: "3.10"
          - os: "ubuntu-20.04"
            python-version: "3.11"
          - os: "ubuntu-22.04"
            python-version: "3.12"
    defaults:
      run:
        shell: bash -l {0}
    name: conda_install on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge
          environment-file: environment.yml
      - name: Install pmpm
        run: pip install .
      - name: test
        # TODO: make ipykernel optional
        run: |
          pmpm \
            conda_install \
            "$HOME/pmpm-test" \
            --conda-channels conda-forge \
            --conda-dependencies ipykernel \
            --dependencies \
            --python-version ${{ matrix.python-version }} \
            --conda mamba \
            --skip-test \
            --arch x86-64-v2 \
            --tune generic
        env:
          # c.f. https://github.com/hpc4cmb/toast/blob/eb1e65097f99ecac63d8976f7131764a43a7ff07/src/toast/tests/runner.py#L113-L117
          CIBUILDWHEEL: 1
